def get_traducciones():
    return {
        "español": {
            "titulo": "Interfaz PDF/Foto y Texto",
            "subir_imagen": "Sube una imagen del formulario",
            "imagen_subida": "Imagen subida",
            "seleccionar_idioma": "Selecciona un idioma:",
            "titulo_pdf": "Visualización de PDF o Imagen",
            "cambiar_pdf": "Cambiar PDF",
            "mostrando_pdf_original": "Mostrando PDF Original",
            "mostrando_pdf_traducido": "Mostrando PDF Traducido",
            "contenido_txt": "Contenido del archivo TXT",
            "texto_area": "Texto del archivo",
            "warning_imagen": "Por favor, sube una imagen para continuar.",
        },
        "frances": {
            "titulo": "Interface PDF/Photo et Texte",
            "subir_imagen": "Téléchargez une image du formulaire",
            "imagen_subida": "Image téléchargée",
            "seleccionar_idioma": "Sélectionnez une langue:",
            "titulo_pdf": "Affichage du PDF ou de l'image",
            "cambiar_pdf": "Changer PDF",
            "mostrando_pdf_original": "Affichage du PDF original",
            "mostrando_pdf_traducido": "Affichage du PDF traduit",
            "contenido_txt": "Contenu du fichier TXT",
            "texto_area": "Texte du fichier",
            "warning_imagen": "Veuillez télécharger une image pour continuer.",
        },
        "aleman": {
            "titulo": "PDF/Foto und Text Schnittstelle",
            "subir_imagen": "Lade ein Bild des Formulars hoch",
            "imagen_subida": "Hochgeladenes Bild",
            "seleccionar_idioma": "Wählen Sie eine Sprache:",
            "titulo_pdf": "PDF oder Bildanzeige",
            "cambiar_pdf": "PDF wechseln",
            "mostrando_pdf_original": "Original-PDF anzeigen",
            "mostrando_pdf_traducido": "Übersetztes PDF anzeigen",
            "contenido_txt": "Inhalt der TXT-Datei",
            "texto_area": "Dateitext",
            "warning_imagen": "Bitte lade ein Bild hoch, um fortzufahren.",
        },
        "arabe": {
            "titulo": "واجهة PDF/صورة ونص",
            "subir_imagen": "حمّل صورة النموذج",
            "imagen_subida": "الصورة المرفوعة",
            "seleccionar_idioma": "اختر لغة:",
            "titulo_pdf": "عرض PDF أو الصورة",
            "cambiar_pdf": "تغيير PDF",
            "mostrando_pdf_original": "عرض PDF الأصلي",
            "mostrando_pdf_traducido": "عرض PDF المترجم",
            "contenido_txt": "محتوى ملف TXT",
            "texto_area": "نص الملف",
            "warning_imagen": "يرجى تحميل صورة للمتابعة.",
        },
        "chino_mandarin": {
            "titulo": "PDF/图片和文本界面",
            "subir_imagen": "上传表格图片",
            "imagen_subida": "上传的图片",
            "seleccionar_idioma": "选择一种语言:",
            "titulo_pdf": "PDF或图片显示",
            "cambiar_pdf": "切换 PDF",
            "mostrando_pdf_original": "显示原始 PDF",
            "mostrando_pdf_traducido": "显示翻译后的 PDF",
            "contenido_txt": "TXT文件内容",
            "texto_area": "文件文本",
            "warning_imagen": "请上传一张图片以继续。",
        },
        "ingles": {
            "titulo": "PDF/Photo and Text Interface",
            "subir_imagen": "Upload an image of the form",
            "imagen_subida": "Image uploaded",
            "seleccionar_idioma": "Select a language:",
            "titulo_pdf": "Display of PDF or Image",
            "cambiar_pdf": "Change PDF",
            "mostrando_pdf_original": "Showing Original PDF",
            "mostrando_pdf_traducido": "Showing Translated PDF",
            "contenido_txt": "TXT file content",
            "texto_area": "File text",
            "warning_imagen": "Please upload an image to continue.",
        }
    }
